### PR TITLE
fix: running all tests [IA-160]

### PR DESCRIPTION
**Pull request by AlexWeinstein92**

### CODE REVIEW

**Comment by miguelTaningcoYoppworks** [comment]
Since we're focussing on build.sbt and Helpers in this PR, I'll just make a comment for making sure it's written somewhere. I noticed that gateway subproject doesn't use the -Werror command which means that a lot of warnings found in gateway is being ignored. So either add -Werror in this PR or make a separate ticket addressing this since I tried to add it in myself but some of the errors were out of my area of concern.

**Comment by dag-yoppworks** [comment]
The issue with the broken build is an urgent fix and the warnings not being errors is not, so I'd lean towards separating that fix out into its own PR.

**Comment by AlexWeinstein92** [comment]
@miguelTaningcoYoppworks @dag-yoppworks with `wErrors` enabled, there is not much to change. It is really just dependencies that aren't used in one file.

HOWEVER - there is a warning that sbt always gives for the dependency `import io.circe.generic.auto._`. This import is necessary and breaks IntelliJ when taken out on lines where `case class`es are decoded or encoded using circe's autoderivation.

I am not really sure what to do about this. Circe autoderivation seems to break `wErrors`... @reid-spencer maybe you have some advice?

**Review by miguelTaningcoYoppworks — APPROVED** [review]
LGTM after the -Werror issue that Alex mentioned is somehow addressed or discussed elsewhere.

**Pull request merged**
